// frontend/src/BubbleLegend.tsx
import { ScalePower, select, Selection } from 'd3'
import { useEffect, useRef } from 'react'

function drawBubbleLegend(
    g: Selection<SVGGElement | null, unknown, null, undefined>,
    radius: ScalePower<number, number, never>,
    title: string
) {
    const legend = g
        .attr('fill', '#777')
        .attr('transform', 'translate(915,508)')
        .attr('text-anchor', 'middle')
        .style('font', '10px sans-serif')
        .selectAll('g')
        .data(radius.ticks(4).slice(1))
        .join('g')

    legend.selectAll('*').remove()

    g.selectAll('text')
        .data([title])
        .join('text')
        .attr('y', -90)
        .text((d) => d)

    legend
        .append('circle')
        .attr('fill', 'none')
        .attr('stroke', '#ccc')
        .attr('cy', (d) => -radius(d))
        .attr('r', radius)

    legend
        .append('text')
        .attr('y', (d) => -2 * radius(d))
        .attr('dy', '1.3em')
        .text(radius.tickFormat(4, 's'))
}

type Props = { radius: ScalePower<number, number, never>; title: string }

function BubbleLegend({ radius, title }: Props) {
    const gRef = useRef<SVGGElement>(null)
    useEffect(() => {
        const g = select(gRef.current)
        drawBubbleLegend(g, radius, title)
    }, [radius, title])

    return <g id="bubble-legend" ref={gRef} />
}

export default BubbleLegend

// test-svelte/src/BubbleLegend.svelte
<script lang="ts">
    import type { ScalePower } from "d3";

    export let radius: ScalePower<number, number, never>;
    export let title: string;

    // start > 0 so we don't have a circle of radius 0
    $: ticks = radius.ticks(4).slice(1);
</script>

<g id="bubble-legend" fill="currentColor" transform="translate(915, 508)">
    {#each ticks as tick}
        <g>
            <circle cy={-radius(tick)} r={radius(tick)} stroke="currentColor" />
            <text y={-2 * radius(tick)} dy="1.3em">
                {radius.tickFormat(4, "s")(tick)}
            </text>
        </g>
    {/each}
    <text y="-90">{title}</text>
</g>

<style>
    #bubble-legend {
        text-anchor: middle;
        font-size: 10px;
    }

    circle {
        fill: none;
    }
</style>
