// src/Map.tsx
import React, { useRef, useEffect } from 'react';
import { select, geoPath, scaleThreshold, schemeBlues } from 'd3';
import { feature } from 'topojson-client';
import { Objects, Topology, GeometryCollection } from 'topojson-specification';
import { GeoJsonProperties } from 'geojson';

const getColor = scaleThreshold<number, string>()
    .domain([0, 1000000, 2000000, 3000000, 10000000, 100000000, 300000000, 700000000])
    .range(schemeBlues[9]);

const Map = ({data}: {data: Topology<Objects<GeoJsonProperties>> | undefined}) => {
    const svgRef = useRef<SVGSVGElement>(null);

    useEffect(() => {
        const svg = select(svgRef.current);

        if (data === undefined) {
            return;
        }
        const countyGeoJson = feature(
            data,
            data.objects.counties as GeometryCollection<GeoJsonProperties>
        )
        svg.attr("viewBox", "0, 0, 975, 610")
        .attr("id", "map")
            .append("g")
            .attr("id", "map")
            .selectAll("path")
            .data(countyGeoJson.features)
            .join("path")
            .attr("class", "county")
            .attr("fill", d => {
                if (d.properties) {
                    return getColor(d.properties["GDP2018"]);
                } else {
                    return getColor(0);
                }
            })
            .attr("d", geoPath())
    }, [data])

    return <svg ref={svgRef}></svg>
}

export default Map;

// test-svelte/src/Map.svelte
<script lang="ts">
    import { geoPath } from "d3";
    import type { Data } from "./DataApi";
    import EmptyMap from "./EmptyMap.svelte";
    import FullMap from "./FullMap.svelte";
    import type { MapConfig } from "./MapConfigApi";
    import usa from "./usa.json";
    import type {
        GeometryCollection,
        Objects,
        Topology,
    } from "topojson-specification";
    import { feature } from "topojson-client";
    import type { GeoJsonProperties } from "geojson";
    import type { County } from "./Counties";

    export let mapInfo:
        | { data: Promise<Data>; mapConfig: MapConfig }
        | undefined;

    const path = geoPath();
    const topoJson = usa as any as Topology<Objects<GeoJsonProperties>>;
    const countyFeatures = feature(
        topoJson,
        topoJson.objects.counties as GeometryCollection<GeoJsonProperties>
    ).features;
    const countyPaths: County[] = countyFeatures.map((feature) => ({
        id: feature.id as string,
        path: path(feature) as string,
    }));
</script>

<svg viewBox="0, 0, 1175, 610" xmlns="http://www.w3.org/2000/svg">
    {#if mapInfo}
        {#await mapInfo.data}
            <EmptyMap counties={countyPaths} />
        {:then data}
            <FullMap {data} mapConfig={mapInfo.mapConfig} {countyPaths} />
        {/await}
    {:else}
        <EmptyMap counties={countyPaths} />
    {/if}
</svg>

<style>
    svg {
        min-width: 500px;
        width: 100%;
        align-self: flex-start;
    }
</style>
