// frontend/src/StateMap.tsx
import { geoPath } from 'd3'
import { mesh } from 'topojson-client'
import type { GeometryCollection } from 'topojson-specification'
import { TopoJson } from './TopoJson'

function StateMap({ topoJson, transform }: { topoJson: TopoJson; transform?: string }) {
    return (
        <g id="states" transform={transform}>
            <path
                d={
                    geoPath()(
                        mesh(
                            topoJson,
                            topoJson.objects.states as GeometryCollection,
                            (a, b) => a !== b
                        )
                    )!
                }
                stroke="white"
                fill="none"
                strokeLinejoin="round"
            />
        </g>
    )
}
export default StateMap

// test-svelte/src/StateMap.svelte
<script lang="ts">
    import { geoPath } from "d3";

    import { mesh } from "topojson-client";
    import type { GeometryCollection } from "topojson-specification";
    import type { TopoJson } from "./MapUtils";

    export let topoJson: TopoJson;

    $: statePath = geoPath()(
        mesh(
            topoJson,
            topoJson.objects.states as GeometryCollection,
            (a, b) => a !== b
        )
    )!;
</script>

<g id="states">
    <path d={statePath} stroke="#777" fill="none" stroke-linejoin="round" />
</g>
