// test-svelte/src/Legend.svelte
<script lang="ts">
    import * as d3 from "d3";
    import LegendTicks from "./LegendTicks.svelte";
    import { ramp } from "./LegendUtils";
    export let color: any;
    export let title: string;
    export let tickSize = 6;
    export let width = 345;
    export let height = 54 + tickSize;
    export let marginTop = 28;
    export let marginRight = 10;
    export let marginBottom = 16 + tickSize;
    export let marginLeft = 10;
    export let ticks = width / 64;
    export let tickFormat: (n: number | { valueOf(): number }) => string;
    export let showHighLowLabels = false;

    let xScale: any;
    let tickValues: number[] | undefined;

    const BACKGROUND_COLOR = "rgba(25, 25, 25, .8)";

    $: {
        if (color.interpolator) {
            xScale = Object.assign(
                color
                    .copy()
                    .interpolator(
                        d3.interpolateRound(marginLeft, width - marginRight)
                    ),
                {
                    range() {
                        return [marginLeft, width - marginRight];
                    },
                }
            );

            // scaleSequentialQuantile doesn’t implement ticks.
            if (!xScale.ticks) {
                const n = Math.round(ticks + 1);
                tickValues = d3
                    .range(n)
                    .map(
                        (i) =>
                            d3.quantile(color.domain(), i / (n - 1)) as number
                    );
            }
        } else if (color.invertExtent) {
            const thresholds = color.thresholds
                ? color.thresholds() // scaleQuantize
                : color.quantiles
                ? color.quantiles() // scaleQuantile
                : color.domain(); // scaleThreshold

            xScale = d3
                .scaleLinear()
                .domain([-1, color.range().length - 1])
                .rangeRound([marginLeft, width - marginRight]);

            tickValues = d3.range(thresholds.length);
            const originalTickFormat = tickFormat;
            tickFormat = (i) => originalTickFormat(thresholds[i.valueOf()]);
        }
    }

    const colorCast = (color: any) => color as string | undefined;
</script>

<svg
    id="legend"
    x="550"
    y="20"
    {width}
    {height}
    viewBox={"0 0 " + width + " " + height}
>
    <rect width="100%" height="100%" fill={BACKGROUND_COLOR} />
    {#if color.interpolator}
        <image
            x={marginLeft}
            y={marginTop}
            width={width - marginLeft - marginRight}
            height={height - marginTop - marginBottom}
            preserveAspectRatio="none"
            xlink:href={ramp(color.interpolator()).toDataURL()}
        />
    {:else if color.invertExtent}
        <g>
            {#each color.range() as color, i (i)}
                <rect
                    x={xScale(i - 1)}
                    y={marginTop}
                    width={xScale(i) - xScale(i - 1)}
                    height={height - marginTop - marginBottom}
                    fill={colorCast(color)}
                />
            {/each}
        </g>
    {/if}
    <LegendTicks
        {height}
        {width}
        {marginBottom}
        {marginLeft}
        {marginRight}
        {marginTop}
        {title}
        {xScale}
        {tickFormat}
        numTicks={ticks}
        {tickSize}
        {tickValues}
        {showHighLowLabels}
    />
</svg>

<style>
    #legend {
        display: block;
        overflow: visible;
    }
</style>

// src/Legend.tsx
import React, { useEffect, useRef } from "react";
import * as d3 from "d3";
import { select } from "d3";
import { IconButton, makeStyles, Tooltip } from "@material-ui/core";
import { Info } from "@material-ui/icons";

type Props = {
    color: any,
    title: string,
    tickSize?: number,
    width?: number,
    height?: number,
    marginTop?: number,
    marginRight?: number,
    marginBottom?: number,
    marginLeft?: number,
    ticks?: number,
    tickFormat?: any,
    tickValues?: any,
    showTooltip?: boolean,
};

const useTooltipStyles = makeStyles(theme => ({
    arrow: {
      color: theme.palette.common.black,
    },
    tooltip: {
      backgroundColor: theme.palette.common.black,
      fontSize: theme.typography.fontSize,
    },
}));

const Legend = ({
    color,
    title,
    tickSize = 6,
    width = 320,
    height = 44 + tickSize,
    marginTop = 18,
    marginRight = 0,
    marginBottom = 16 + tickSize,
    marginLeft = 0,
    ticks = width / 64,
    tickFormat,
    tickValues,
    showTooltip,
}: Props) => {
    const tooltipClasses = useTooltipStyles();
    const svgRef = useRef<SVGSVGElement>(null);
    useEffect(() => {
        const svg = select(svgRef.current);

        svg.selectAll("*").remove();

        let tickAdjust = (g: any) => g.selectAll(".tick line").attr("y1", marginTop + marginBottom - height);
        let x: any;

        // Continuous
        if (color.interpolate) {
            const n = Math.min(color.domain().length, color.range().length);

            x = color.copy().rangeRound(d3.quantize(d3.interpolate(marginLeft, width - marginRight), n));

            svg.append("image")
                .attr("x", marginLeft)
                .attr("y", marginTop)
                .attr("width", width - marginLeft - marginRight)
                .attr("height", height - marginTop - marginBottom)
                .attr("preserveAspectRatio", "none")
                .attr("xlink:href", ramp(color.copy().domain(d3.quantize(d3.interpolate(0, 1), n))).toDataURL());
        }

        // Sequential
        else if (color.interpolator) {
            x = Object.assign(color.copy()
                .interpolator(d3.interpolateRound(marginLeft, width - marginRight)),
                { range() { return [marginLeft, width - marginRight]; } });

            svg.append("image")
                .attr("x", marginLeft)
                .attr("y", marginTop)
                .attr("width", width - marginLeft - marginRight)
                .attr("height", height - marginTop - marginBottom)
                .attr("preserveAspectRatio", "none")
                .attr("xlink:href", ramp(color.interpolator()).toDataURL());

            // scaleSequentialQuantile doesn’t implement ticks or tickFormat.
            if (!x.ticks) {
                if (tickValues === undefined) {
                    const n = Math.round(ticks + 1);
                    tickValues = d3.range(n).map(i => d3.quantile(color.domain(), i / (n - 1)));
                }
                if (typeof tickFormat !== "function") {
                    tickFormat = d3.format(tickFormat === undefined ? ",f" : tickFormat);
                }
            }
        }

        // Threshold
        else if (color.invertExtent) {
            const thresholds
                = color.thresholds ? color.thresholds() // scaleQuantize
                    : color.quantiles ? color.quantiles() // scaleQuantile
                        : color.domain(); // scaleThreshold

            const thresholdFormat
                = tickFormat === undefined ? (d: any) => d
                    : typeof tickFormat === "string" ? d3.format(tickFormat)
                        : tickFormat;

            x = d3.scaleLinear()
                .domain([-1, color.range().length - 1])
                .rangeRound([marginLeft, width - marginRight]);

            svg.append("g")
                .selectAll("rect")
                .data(color.range())
                .join("rect")
                .attr("x", (d, i) => x(i - 1))
                .attr("y", marginTop)
                .attr("width", (d, i) => x(i) - x(i - 1))
                .attr("height", height - marginTop - marginBottom)
                .attr("fill", (d: any) => d);

            tickValues = d3.range(thresholds.length);
            tickFormat = (i: number) => thresholdFormat(thresholds[i], i);
        }

        // Ordinal
        else {
            x = d3.scaleBand()
                .domain(color.domain())
                .rangeRound([marginLeft, width - marginRight]);

            svg.append("g")
                .selectAll("rect")
                .data(color.domain())
                .join("rect")
                .attr("x", x)
                .attr("y", marginTop)
                .attr("width", Math.max(0, x.bandwidth() - 1))
                .attr("height", height - marginTop - marginBottom)
                .attr("fill", color);

            tickAdjust = () => { };
        }

        svg.append("g")
            .attr("transform", `translate(0,${height - marginBottom})`)
            .call(d3.axisBottom(x)
                .ticks(ticks, typeof tickFormat === "string" ? tickFormat : undefined)
                .tickFormat(typeof tickFormat === "function" ? tickFormat : undefined)
                .tickSize(tickSize)
                .tickValues(tickValues))
            .call(tickAdjust)
            .call(g => g.select(".domain").remove())
            .call(g => g.append("text")
                .attr("x", marginLeft)
                .attr("y", marginTop + marginBottom - height - 6)
                .attr("font-size", 14)
                .attr("fill", "currentColor")
                .attr("text-anchor", "start")
                .attr("class", "title")
                .text(title));
    });
    return <React.Fragment><svg
        id="legend"
        x="550"
        y="20"
        width={width}
        height={height}
        viewBox={"0 0 " + width + " " + height}
        overflow="visible"
        display="block"
        ref={svgRef} />
        {
            showTooltip &&
            <foreignObject x="500" y="20" width="46" height="46">
                <Tooltip
                    classes={tooltipClasses}
                    arrow
                    placement="top"
                    title="The normalized value is the percentile
                            of the raw data. If you select multiple data,
                            we take the mean of the percentiles.">
                    <IconButton aria-label="info">
                        <Info />
                    </IconButton>
                </Tooltip>
            </foreignObject>
        }
        </React.Fragment>;
}

function ramp(color: any, n = 256) {
    var canvas = document.createElement('canvas');
    canvas.width = n;
    canvas.height = 1;
    const context = canvas.getContext("2d");
    if (context) {
        for (let i = 0; i < n; ++i) {
            context.fillStyle = color(i / (n - 1));
            context.fillRect(i, 0, 1, 1);
        }
    }
    return canvas;
}

export default Legend;
